---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netmon
  namespace: netmon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: netmon
  name: pod-lister-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-lister-binding
  namespace: netmon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lister-role
subjects:
  - kind: ServiceAccount
    name: netmon
    namespace: netmon 
